### ISSUE TITLE
problem - when first setup 

### ISSUE THREAD

**Issue by MuhamedMohsen** [LaravelDaily/Laravel-Appointments#1]
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/pdf-to-image 1.8.2 -> satisfiable by spatie/pdf-to-image[1.8.2].
    - spatie/pdf-to-image 1.8.2 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
  Problem 2
    - spatie/pdf-to-image 1.8.2 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - spatie/laravel-medialibrary 7.12.1 requires spatie/pdf-to-image ^1.2 -> satisfiable by spatie/pdf-to-image[1.8.2].
    - Installation request for spatie/laravel-medialibrary 7.12.1 -> satisfiable by spatie/laravel-medialibrary[7.12.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by PovilasKorop** [comment]
@MuhamedMohsen currently the package we use for file uploads is requiring additional PHP library ImageMagick. Here are instructions for xampp: https://gist.github.com/tojibon/326d1df3d9a260fc3bdf (haven't tried myself, just googled it)
