### ISSUE TITLE
Uploading Photos For Employees

### ISSUE THREAD

**Issue by SmoofOperator** [LaravelDaily/Laravel-Appointments#2]
When uploading photos for employees the links point to the incorrect url.

**Comment by PovilasKorop** [comment]
@IsabelleCarlsson what exactly incorrect URL? Have you run `php artisan storage:link`?

**Comment by SmoofOperator** [comment]
@PovilasKorop Yes, I have. However the image doesn't point to the correct url i.e. the host `https://test.test/storage/id...` in my case. Instead of using a static localhost address which results in a broken link when viewing the image or thumbnail you can append the `storage/id`.

Example of viewing the image:
[https://imgur.com/a/dSk2sxr](https://imgur.com/a/dSk2sxr)

**Comment by PovilasKorop** [comment]
@IsabelleCarlsson have you set up your host in `.env` file under `APP_URL` variable? What is the value there?

**Comment by SmoofOperator** [comment]
That's it! Thanks.
