### ISSUE TITLE
Its possible to use without quick admin generator?

### ISSUE THREAD

**Issue by samuk190** [LaravelDaily/Laravel-Appointments#3]
I have another project which I have default auth from laravel and I want to use this package

**Comment by PovilasKorop** [comment]
@samuk190 this project is a full demo0project generated with quick admin generator, not a package. It's not installable in other existing project, unless you want to copy-paste the code part by part.

But it can be used by itself, without quick admin generator.

**Comment by samuk190** [comment]
Thanks!
