### ISSUE TITLE
Appointements index view Error

### ISSUE THREAD

**Issue by ridaouiafaf** [LaravelDaily/Laravel-Appointments#7]
when oppening the route admin.appointements.index there's a ajax datatable error that appears
![image](https://user-images.githubusercontent.com/54274365/87881222-be94a200-c9ef-11ea-8ec8-16392a4e54e7.png)

**Comment by PovilasKorop** [comment]
@ridaouiafaf that error means something is wrong with some date format, some date field is either empty or in a wrong format. Please debug.

**Comment by masterelahee** [comment]
![image](https://user-images.githubusercontent.com/48475261/95178321-e24ad580-07f1-11eb-86f5-0a3507a432df.png)

There is this error even on a fresh copy of the site, after clicking on clients, appointments and employees. Other than that works fine.
